# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "hotfix" ]
    paths:
      - "src/**"
  pull_request:
    branches: [ "main", "hotfix" ]
    paths:
      - "src/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      
      - name: Install luacc
        run: luarocks install luacc
      
      - name: Install luamin
        run: sudo yarn global add https://github.com/cyberbit/luamin

      - name: Build
        run: ./build.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev
          path: dist/*.lua
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist/release/*.lua
      
      # via https://github.com/softprops/action-gh-release/issues/270
      - name: Create tag
        id: tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          TAG=v0.0.0+$(date -Iseconds | sed 's/[-T:\+]//g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG
      
      - name: Release!
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          prerelease: true
          draft: true
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            dist/notes.lua
            dist/vendor.lua
            dist/release/notes.min.lua
            dist/release/vendor.min.lua
